# Generated by Django 2.2.20 on 2021-09-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Elonlar Kategoriyalari'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='elonimages'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='elonimages'),
        ),
    ]
