# Generated by Django 3.2.7 on 2021-09-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='cost',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
