# Generated by Django 2.2.20 on 2021-09-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_auto_20210928_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': ' Blog Kategoriyalari'},
        ),
    ]
